name: PresentationLayer

include:
  - path: ../ProjectCommon.yml

options:
  createIntermediateGroups: true

targets:
  PresentationLayer:
    templates:
      - WithUnitAndUITests
    platform: iOS
    type: application
    sources: PresentationLayer
    dependencies:
      - framework: libDomainLayer.a
        implicit: true
      - framework: DataLayer.framework
        implicit: true
      - package: RxSwift
      - package: RxCocoa
  PresentationLayerTests:
    platform: iOS
    type: bundle.unit-test
    sources: PresentationLayerTests
    dependencies:
      - target: PresentationLayer
        embed: false
  PresentationLayerUITests:
    platform: iOS
    type: bundle.ui-testing
    sources: PresentationLayerUITests
    dependencies:
      - target: PresentationLayer
