name: DataLayer

include:
  - path: ../ProjectCommon.yml

targets:
  DataLayer:
    templates:
      - WithUnitTest
    platform: iOS
    type: framework.static
    sources: DataLayer
    dependencies:
      - framework: libDomainLayer.a
        implicit: true
      - package: RxSwift
      - package: RxCocoa
  DataLayerTests:
    platform: iOS
    type: bundle.unit-test
    sources: DataLayerTests
    dependencies:
      - target: DataLayer
        embed: false
